# Site settings
title: Alice Pote
email: alice.writes.wrongs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Code, math, and musings of an aspiring software developer and free
    software enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "aliceriot.github.io" # the base hostname & protocol for your site
timezome: America/New_York
default_column: "one"

# Build settings
markdown: kramdown
paginate: 5
highlighter: pygments

#account info
github_username:  aliceriot

